apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "harness-ccm-autostopping.fullname" . }}-secret-reader
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "harness-ccm-autostopping.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - delete
      - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "harness-ccm-autostopping.fullname" . }}
rules:
  - apiGroups:
      - ccm.harness.io
    resources:
      - autostoppingrules
      - autostoppingrules/status
    verbs:
      - get
      - list
      - watch
      - delete
      - create
      - patch
      - update
      - deletecollection
  - apiGroups:
      - networking.k8s.io
      - admissionregistration.k8s.io
      - networking.istio.io
    resources:
      - ingresses
      - validatingwebhookconfigurations
      - virtualservices
      - destinationrules
    verbs:
      - get
      - list
      - watch
      - delete
      - create
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - services
      - namespaces
      - endpoints
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
  - apiGroups:
      - apps
      - extensions
    resources:
      - deployments
      - statefulsets
      - replicasets
      - deployments/scale
      - deployments/status
      - statefulsets/status
      - statefulsets/scale
    verbs:
      - patch
      - update
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch