apiVersion: v1
kind: ConfigMap
metadata:
  # name: {{ include "harness-ccm-autostopping.fullname" . }}-enforcement
  name: harness-autostopping-enforcement
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "harness-ccm-autostopping.labels" . | nindent 4 }}
data:
  is_active: 'false'
  dry_run: enabled
  excluded_namespaces: '[]'
  notifications_enabled: 'false'
  notifications_usergroups: '[]'