apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "harness-ccm-autostopping.router.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "harness-ccm-autostopping.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "harness-ccm-autostopping.router.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.router.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "harness-ccm-autostopping.router.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.router.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.router.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "harness-ccm-autostopping.router.name" . }}
          securityContext:
            {{- toYaml .Values.router.securityContext | nindent 12 }}
          image: "{{ .Values.router.image.repository }}:{{ .Values.router.image.tag }}"
          imagePullPolicy: {{ .Values.router.image.pullPolicy }}
          command:
          - envoy
          args:
          - -c
          - /etc/envoy.yaml
          ports:
          - containerPort: 10000
            protocol: TCP
            name: listener
          - containerPort: 9901
            protocol: TCP
            name: admin
          resources:
            {{- toYaml .Values.router.resources | nindent 12 }}
          volumeMounts:
          - name: as-router-config
            mountPath: /etc/envoy.yaml
            subPath: envoy.yaml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: as-router-config
        configMap:
          name: {{ include "harness-ccm-autostopping.router.name" . }}
          defaultMode: 420
      {{- with .Values.router.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.router.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.router.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
