apiVersion: v1
kind: Service
metadata:
  # name: {{ include "harness-ccm-autostopping.router.name" . }}
  name: autostopping-router
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "harness-ccm-autostopping.labels" . | nindent 4 }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 10000
  selector:
    {{- include "harness-ccm-autostopping.router.selectorLabels" . | nindent 6 }}
  type: ClusterIP