{{- if not .Values.existingApiKey }}
apiVersion: v1
kind: Secret
metadata:
  # name: {{ include "harness-ccm-autostopping.fullname" . }}
  name: harness-api-key
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "harness-ccm-autostopping.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.apiToken }}
{{- end }}